parameters:
    product_directory: '%kernel.root_dir%../web/uploads/product'
    product_category_directory: '%kernel.root_dir%../web/uploads/product-category'

twig:
    globals:
        uploads_directory: '/uploads/'

services:
    productsbundle.product_uploader:
        class: ProductsBundle\Services\FileUploader
        arguments: ['%product_directory%']
    productsbundle.product_category_uploader:
        class: ProductsBundle\Services\FileUploader
        arguments: ['%product_category_directory%']