<?php

namespace ProductsBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllWithImagesOrderedByRank()
    {
        $qb = $this->createQueryBuilder('p');
        $qb->where('p.image != :identifier')
            ->setParameter('identifier', '<null>');
        $qb->orderBy('p.rank');

        return $qb->getQuery()->getResult();
    }
}
