<?php

namespace ProductsBundle\Repository;

/**
 * ProductCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllWithImagesOrderedByRank()
    {
        $qb = $this->createQueryBuilder('pc');
        $qb->where('pc.image != :identifier')
            ->setParameter('identifier', '<null>');
        $qb->orderBy('pc.rank');

    return $qb->getQuery()->getResult();
    }

}